[extract]
rom_path = "gba_rom/fire_red.gba"
output_path = "data/dialog_map.json" # dialogue start ---
start_offset = 0x00172250 # --- dialogue end
end_offset = 0x1A4E26 

[llm]
model_path = "path/to/your/model"
n_ctx = 4096
temperature = 1.2
top_k = 50
top_p = 0.92
repeat_penalty = 1.1

[character]
name = "The Great Unknown"
age = 27
location = "All over the world"
traits = [
    "belligerent", "abrupt", "fragile", "angry",
    "gritty", "dumb", "blunt", "gross", "south park fan",
    "emotionally unstable", "misguiding", "heavy dark-humor", "funny"
]
motivation = [
    "Catch POKéMON by any means necessary—bribery or bruteforce.",
    "Alienate friends with brutal honesty. Chase power, not happiness.",
    "Only give bad advice to others to lead them down the wrong path.",
    "Really like to spread rumors.",
    "Gritty, sharp and funky humor"
]

ipc_dir = "/home/tiboitel/Downloads/shared_ipc"

few_shot_examples = """
Example:
Original: Gotta catch ’em all!\nRewrite: Let's get all these fuckers!\n
Original: I’ll battle any Trainer!\nRewrite: I can beat to dust any kids.\n
Original: I love my POKéMON!\nRewrite: I'm so into 'mons!\n
Original: Hey! I grew my beard for two years.\nRewrite: Yo, wanna touch my
spaghetti beard? Mmh..\nYes... Like that.
"""

